### ISSUE TITLE
Unable to set custom CA certificate(s) for using the Operator

### ISSUE THREAD

**Issue by rajith77** [keycloak/keycloak-operator#440] opened 2022-01-05 03:35 UTC
### Describe the bug

I have a use case where .x509 Authentication is used in a particular realm.
However the certificates used by these users are signed by a custom CA therefore unable to validate unless Keycloak has access to the CA.

How can we specify this CA cert when using the operator?

In this case the nginx ingress controller is used and therefore we may need to configure the client cert lookup.
How can we configure it when using the operator?
For standalone we use 
{code}
<spi name="x509cert-lookup">
    <default-provider>nginx</default-provider>
    <provider name="nginx" enabled="true">
        <properties>
            <property name="sslClientCert" value="ssl-client-cert"/>
            <property name="sslCertChainPrefix" value="USELESS"/>
            <property name="certificateChainLength" value="2"/>
        </properties>
    </provider>
</spi>
{code}
### Version

14.0.0

### Expected behavior

Ability to add CA cert to the trust store as well as configure the client cert lookup.

**Comment by andreaTP** [comment] 2022-01-21 10:08
Hi @rajith77 ,

thanks for opening this issue, I have to ask you if you can edit the description to include the missing `code` snippet.

Are you trying to add certificates to the Keycloak truststore?
In this case it's already supported and can be achieved by injecting environment variables and mounting additional volumes in the keycloak deployment pods ( some initial documentation can be found [here](https://github.com/keycloak/keycloak-containers/blob/a03d3e8c54c3ad364d4ee912fca0298bc5a7099c/server/README.md#setting-up-tlsssl) ).

**Comment by andreaTP** [comment] 2022-02-15 10:57
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:57 UTC
Labels: kind/bug
