### ISSUE TITLE
Keycloak POD intermittently restarted because PostgreSQL POD is not yet ready

### ISSUE THREAD

**Issue by tommaso-borgato** [keycloak/keycloak-operator#407] opened 2021-11-29 09:40 UTC
### Describe the bug

The **Keycloak POD** connects via **JDBC** to the **PostgreSQL POD**;
It may happen that, if the **PostgreSQL POD** isn't yet ready when the **Keycloak POD** tries to connect to it, then the **Keycloak POD** fails and needs to be restarted;
This introduces a delay of several minutes before the **Keycloak POD** is actually ready to server requests and the **Keycloak POD** has the Restarts count set to 1 (instead of 0)

### Version

15.0.2 (rhsso-operator.7.5.1-opr-001)

### Expected behavior

no restart of **Keycloak POD** is needed

### How to Reproduce?

```
oc new-project rhsso-operator-issue

cat <<EOT > OperatorGroup.yaml
apiVersion: "operators.coreos.com/v1"
kind: "OperatorGroup"
metadata:
  name: "rhsso-operator-issue-operators"
  namespace: "rhsso-operator-issue"
spec:
  targetNamespaces:
  - "rhsso-operator-issue"
EOT  

oc apply -f OperatorGroup.yaml
```

Using Keycloak image registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:

```
cat <<EOT > Subscription.yaml 
apiVersion: "operators.coreos.com/v1alpha1"
kind: "Subscription"
metadata:
  name: "rhsso-operator"
  namespace: "rhsso-operator-issue"
spec:
  channel: "alpha"
  config:
    env:
    - name: "PROFILE"
      value: "RHSSO"
    - name: "RELATED_IMAGE_RHSSO"
      value: "registry.redhat.io/rh-sso-7/sso74-openshift-rhel8:latest"
  name: "rhsso-operator"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
EOT

oc apply -f Subscription.yaml
  
cat <<EOT > Keycloak.yaml   
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-sso
  namespace: rhsso-operator-issue
spec:
  externalAccess:
    enabled: true
  instances: 1    
EOT

oc apply -f Keycloak.yaml
```

Then with `oc get pods` you observe:

both keycloak and keycloak-postgresql pods are starting:

```
Name					Status		Ready	Restarts
keycloak-0				Running		0/1	0
keycloak-postgresql-6d966cb4fb-869bq	Running		0/1	0
rhsso-operator-56bf8c94df-n52dg		Running		1/1	0
```
then only the keycloak-postgresql pods becomes ready:

```
Name					Status		Ready	Restarts
keycloak-0				Running		0/1	0
keycloak-postgresql-6d966cb4fb-869bq	Running		1/1	0
rhsso-operator-56bf8c94df-n52dg		Running		1/1	0
```

meanwhile In `keycloak-0` log pod you see:

`[0m[31m16:36:08,386 FATAL [com.arjuna.ats.arjuna] (MSC service thread 1-1) ARJUNA012260: Received exception for com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DataSourceJDBCAccess:oskeycloak0JBossTSTxTable: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDSObjectStore`

Finally, after `keycloak-0` is restarted (takes several minutes):

```
Name					Status		Ready	Restarts
keycloak-0				Running		1/1	1	
keycloak-postgresql-6d966cb4fb-869bq	Running		1/1	0
rhsso-operator-56bf8c94df-n52dg		Running		1/1	0
```

Using Keycloak image registry.redhat.io/rh-sso-7/sso75-openshift-rhel8 (the default image) we were able to reproduce the bug by deleting and the recreating the Keycloak custom resource;

**Comment by andreaTP** [comment] 2021-12-22 12:08
Hi @tommaso-borgato ,

thanks for opening this issue, for production purposes we encourage our users to provide an `externalDatabase`.
Can you verify that you can reproduce the behaviour with this more "production-ready" configuration?

**Comment by andreaTP** [comment] 2022-02-15 10:56
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:56 UTC
Labels: impact/low, kind/bug
