### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak-operator#457] opened 2022-01-25 08:25 UTC
### Description

is it possible to add a helm chart for the operator ?

### Motivation

The OLM thinks the operator is namespace scoped, so I rather not use it. (maybe this can be fixed two)
A helm chart allows for easier cluster automation/bootstrap.

**Comment by andreaTP** [comment] 2022-02-04 09:38
Hi @yelhouti ,
to run the operator not namespace scoped you just need to unset the environment variable `WATCH_NAMESPACE` here: https://github.com/keycloak/keycloak-operator/blob/7959cf0f3bfb7b4df4f409bf0371106e886b33cd/deploy/operator.yaml#L24

The preferred and supported way to deploy this operator is using OLM and we don't have capacity to support an additional installer, although you are free to bundle the plain k8s resources available in this repository to fit your needs ( I can find someone already did it in the past: https://github.com/CloudVE/keycloak-operator-helm ).

I hope this answer your question 🙂

**Comment by andreaTP** [comment] 2022-02-15 10:58
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:58 UTC
Labels: impact/low, kind/enhancement, status/hold

**Comment by chris-maclean** [comment] 2022-03-31 17:21
For anyone coming here from Google: I found that in addition unsetting `WATCH_NAMESPACE` (or setting it to `""`), I also had to make minor changes to the Role and RoleBinding resources.

- Role
  - Update `kind` to `ClusterRole`
- RoleBinding
  - Update `kind` to `ClusterRoleBinding`
  - Ensure `subjects[0].namespace` is set to the namespace where the Operator will be deployed

After taking these steps *and* setting `WATCH_NAMESPACE=""`, I was able to deploy the Operator scoped to the entire cluster.
