### ISSUE TITLE
Operator is not synchronizing realm changes to Keycloak

### ISSUE THREAD

**Issue by christianviana** [keycloak/keycloak-operator#453] opened 2022-01-20 15:40 UTC
### Describe the bug

Documentation says that KeycloakRealms are automatically synchronized, but this is not working.

### Version

16.1.0

### Expected behavior

When we apply the changes to the realm CR, the operator should update the realm at Keycloak.

### Actual behavior

After the realm creation, no matter how many times you apply and updated CR, the realm never get updated at Keycloak.
If we delete the CR and create it again, it gets created with the updated information.

Tested fields:
- displayName
- enabled
- registrationAllowed

### How to Reproduce?

- Create a Realm CR yaml file
- Apply the file to create the CR
- Operator will create the realm
- Modify some info at yaml file
- Apply the file to modify the CR
- The CR is updated, but the realm is not change as we can see at web console

### Anything else?

Already reported twice in former issue tracking system:

- [KEYCLOAK-15142](https://issues.redhat.com/browse/KEYCLOAK-15142) 
- [KEYCLOAK-17094](https://issues.redhat.com/browse/KEYCLOAK-17094)

**Comment by neuromantik33** [comment] 2022-01-27 16:12
I know this has been discussed [over and over](https://groups.google.com/g/keycloak-dev/c/6OTpj3ow0u4/m/x2_qCAEEDAAJ?pli=1), but not being able to reconcile realm info makes the operator almost unusable when assigning realm roles and groups. I'm not sure how this operator is better than an helm chart, even clients can't be reconciled. I think the way grafana handles datasources and the such can be an inspiration, ie. certain resources (data sources, dashboards) are either injected as config maps and are immutable from the UI, or anything can be created with the UI but isn't managed by the operator.

**Comment by neuromantik33** [comment] 2022-01-28 10:46
I'll just add that if ansible is able to [reconcile realm state ](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_realm_module.html#ansible-collections-community-general-keycloak-realm-module) I don't see why the operator can't do the same. As is ansible philosophy, if it isn't managed by ansible the latter does to any unmanaged resources.

**Comment by vmuzikar** [comment] 2022-02-03 14:46
This is actually not a bug. Realm's are just created, not updated based on the changes in the CR. It is by design as it's very error prone to do the updates correctly.

Obviously, the bug here is the docs stating that Realms can be updated. This needs to be fixed.

**Comment by vmuzikar** [comment] 2022-02-08 15:22
@rtrive It is really by design. Realms can't be updated using the operator. We plan to take a little bit different approach with the new operator with the static configuration.

The docs will be updated as part of https://github.com/keycloak/keycloak-documentation/pull/1402. After it is merged, we can close this issue.

**Comment by apeschel** [comment] 2022-02-08 18:28
> Keycloak Operator uses a one-way sync for Realms, Clients and Users. The one way sync has been implemented on purpose. Without this approach, any change made manually in the Admin UI would be overridden.

I see overriding manual changes through the UI as an absolute win.

**Closed** 2022-04-20 15:24 UTC
Labels: impact/low, kind/bug
