### ISSUE TITLE
Set "accessType" and "codeChallenge" in KeycloakClient CRD

### ISSUE THREAD

**Issue by abrinckm** [keycloak/keycloak-operator#417] opened 2021-12-13 20:26 UTC
### Description

For app deployments using PKCE flows, I need to be able to create keycloak client with the access type set to "public", and the code challenge set to "S256". These attributes are not present in the KeycloakClient CRD schema that I can see. 

### Motivation

We are deploying applications that have user based accounts as well as backend services that need auth. So we require both the PKCE auth flow (for user accounts) and client credentials (for service auth). Web applications at a large require user login. I feel that if the KeycloakClient CRD only allows for client credentials, then it is not useful beyond machine-to-machine authentication.

**Comment by andreaTP** [comment] 2021-12-22 11:59
Hi @abrinckm ,
to overcome this limitation are you able to set those values using the admin REST api and testing the entire flow?

**Comment by vmuzikar** [comment] 2022-01-03 08:18
@abrinckm This is a small change (I presume only introducing a new field to the CRD to leverage its counterpart in REST API), so we can do it even for the old operator. A PR would be much appreciated! :)

**Comment by andreaTP** [comment] 2022-02-15 10:56
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:56 UTC
Labels: help wanted, kind/enhancement
