### ISSUE TITLE
Authorization policy reconciliation generates an error for own role

### ISSUE THREAD

**Issue by neuromantik33** [keycloak/keycloak-operator#459] opened 2022-01-25 23:03 UTC
### Describe the bug

I'm faced with a sort of chicken & egg problem. I'm trying to reproduce a Keycloak client with authorization enabled using the operator client controller. More specifically, adding an authorization policy role referencing a client role owned by the client. Included are some screenshots of what I'm trying to achieve.
![image](https://user-images.githubusercontent.com/19826274/151072663-3dd62660-e0a2-4654-9f78-6afa2a2a5015.png)
![image](https://user-images.githubusercontent.com/19826274/151072860-9cfdc665-a4ed-4652-8bfd-0e627ec39021.png)

Using the operator to generate this configuration seems impossible atm, since the client roles seem to be reconciled _after_ the fine grained authorization config. Here is the snippet of the KeycloakClient manifest

```yaml
    authorizationSettings:
      allowRemoteResourceManagement: true
      policyEnforcementMode: ENFORCING
      decisionStrategy: UNANIMOUS
      policies:
      - name: Private policy
        type: role
        logic: POSITIVE
        config:
          roles: '[{"id":"student-mgmt/staff","required":true}]'
  roles:
  - name: admin
  - name: public
  - name: staff
```
When attempting to apply the manifest, I get the following exception in keycloak.

```
keycloak-operator-9bf46b547-jdktx keycloak-operator I0125 17:18:11.215571       1 request.go:655] Throttling request took 1.194528325s, request: GET:https://10.143.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.619751,"logger":"controller_keycloakclient","msg":"Reconciling KeycloakClient","Request.Namespace":"keycloak","Request.Name":"student-mgmt"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.6205947,"logger":"controller_keycloakclient","msg":"found 1 matching realm(s) for client keycloak/student-mgmt"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.6209586,"logger":"controller_keycloakclient","msg":"found 1 matching keycloak(s) for realm keycloak/staff-42"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.6547675,"logger":"action_runner","msg":"https://keycloak.keycloak.svc:8443 is not a valid keycloak url : Get https://keycloak.keycloak.svc:8443: x509: certificate is valid for *.42.fr, 42.fr, not keycloak.keycloak.svc"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.694572,"logger":"action_runner","msg":"found keycloak url: https://keycloak-staging.42.fr"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.8956134,"logger":"controller_keycloakclient","msg":"got authenticated client for keycloak at https://keycloak-staging.42.fr"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.895817,"logger":"controller_keycloakclient","msg":"read client state for keycloak keycloak/keycloak, realm keycloak/staff-42, client keycloak/student-mgmt"}
keycloak-operator-9bf46b547-jdktx keycloak-operator {"level":"info","ts":1643131093.9147768,"logger":"action_runner","msg":"(    0)    SUCCESS check if keycloak is available"}
keycloak-0 keycloak 17:18:14,048 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-53) Uncaught server error: java.lang.RuntimeException: Error while updating policy [Private policy]. Role [staff] could not be found.
keycloak-0 keycloak 	at org.keycloak.keycloak-authz-policy-common@16.1.0//org.keycloak.authorization.policy.provider.role.RolePolicyProviderFactory.updateRoles(RolePolicyProviderFactory.java:177)
keycloak-0 keycloak 	at org.keycloak.keycloak-authz-policy-common@16.1.0//org.keycloak.authorization.policy.provider.role.RolePolicyProviderFactory.onImport(RolePolicyProviderFactory.java:108)
keycloak-0 keycloak 	at org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2466)
keycloak-0 keycloak 	at org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:351)
keycloak-0 keycloak 	at org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.models.utils.RepresentationToModel.importPolicies(RepresentationToModel.java:2392)
keycloak-0 keycloak 	at org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2340)
keycloak-0 keycloak 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authorization.admin.ResourceServerService.importSettings(ResourceServerService.java:136)
keycloak-0 keycloak 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.admin.ClientsResource.createClient(ClientsResource.java:199)
keycloak-0 keycloak 	at jdk.internal.reflect.GeneratedMethodAccessor965.invoke(Unknown Source)
keycloak-0 keycloak 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-0 keycloak 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak-0 keycloak 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
...
```
Which I guess it's expected since the client is being created _entirely_ before the roles can be created. If comment out the authorization section and apply the roles, then apply the authorization, I don't see any changes but I'm trying to achieve full versioning for our clients (which will be applied to production as is from git).

### Version

16.1.0

### Expected behavior

I expect the roles and client to be created successfully without exception.

### Actual behavior

See above.

### How to Reproduce?

Create an keycloak client with authorization enabled and a policy referencing a role declared within the same client manifest.

### Anything else?

I would wager the order of the steps specified in `keycloakclient_controller.go` might need some partial application if this is just a limitation of the API.

```go
if state.Client == nil {
    desired.AddAction(i.getCreatedClientState(state, cr))
} else {
    desired.AddAction(i.getUpdatedClientState(state, cr))
}

if state.ClientSecret == nil {
    desired.AddAction(i.getCreatedClientSecretState(state, cr))
} else {
    desired.AddAction(i.getUpdatedClientSecretState(state, cr))
}

i.ReconcileRoles(state, cr, &desired)
```

**Comment by andreaTP** [comment] 2022-02-04 10:27
Hi @neuromantik33 !

Thanks for rising this issue, I do believe that this issue belongs to the main `keycloak/keycloak` repository since, as you mentioned:
> if this is just a limitation of the API.

I encourage you to verify the behaviour using the plain Keycloak API (using the latest released version of it) and rise the issue [here](https://github.com/keycloak/keycloak/issues).

**Comment by andreaTP** [comment] 2022-03-02 11:17
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-03-02 11:17 UTC
Labels: status/hold

**Comment by chris-maclean** [comment] 2022-03-25 20:03
I just wanted to chime in and say that I am experiencing this exact same issue. In my opinion, the issue doesn't lie in the Keycloak API -- creating a Client via the REST API does not allow callers to add Roles to the new Client. See the REST API documentation for the `clients` resource: https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_clients_resource. 

If one were to create both a Client and Client Roles using the Keycloak REST API, they would have to perform separate calls to create the Client, create the Roles (linking to the client via the Client ID), and then update the Client with authorization policies (linking policies to the new Roles via their ID). This is still annoying, but it's clear that the Client and its Roles must be created separately because they can't be submitted at the same time. Creating new Client Roles at the same time as the Client looks to me like a Keycloak-Operator value-add, and it indeed would be very valuable if it worked.

Even if you think the issue does lie with the Keycloak API, the [KeycloakClient CRD](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloakclients_crd.yaml) surely implies that a user can create Client Roles and authorization policies at the same time as the Client. Can this issue be reopened in this repo please?

**Comment by neuromantik33** [comment] 2022-04-04 16:58
I can confirm all of what @chris-maclean has mentioned. It is unfortunate that this issue is closed because it is indeed not a keycloak problem but the operator misorchestrating the steps for client reconciliation.
