### ISSUE TITLE
prometheus service monitor naming

### ISSUE THREAD

**Issue by nemerna** [keycloak/keycloak-operator#448] opened 2022-01-18 11:59 UTC
### Describe the bug

when creating 2 keycloak instances (not 2 replicas) the 2nd instance will try to create same prometheus service monitor
then the operator will fail to create the prometheus resources because they exists and already monitoring the 1st keycloak instance

below is the status of the 2 clusters
**1st cluster:
 message: ''
  phase: reconciling
  ready: true
  secondaryResources:
    ServiceMonitor:
      - keycloak-service-monitor
    PrometheusRule:
      - keycloak**
      

2nd cluster:
 message: >-
    **prometheusrules.monitoring.coreos.com "keycloak" is forbidden: cannot set an
    ownerRef on a resource you can't delete: , <nil>
  phase: failing
  ready: false
  secondaryResources:
    ServiceMonitor:
      - keycloak-service-monitor
    PrometheusRule:
      - keycloak**

### Version

16.1.0

### Expected behavior

create the service monitor/extra resources based on the keycloak cluster name

### Actual behavior

 message: >-
    prometheusrules.monitoring.coreos.com "keycloak" is forbidden: cannot set an
    ownerRef on a resource you can't delete: , <nil>
  phase: failing
  ready: false
  secondaryResources:
    ServiceMonitor:
      - keycloak-service-monitor
    PrometheusRule:
      - keycloak

**Comment by andreaTP** [comment] 2022-01-21 09:44
Hi @nemerna ,

thanks for opening this issue.
Let me ask one question:
Are you installing the 2 instances in the same namespace?

Taking a brief look at the code this feature looks not supported at the moment.

Although you can attempt an __unsupported hack__ by creating a matching `ServiceMonitor` named `keycloak-service-monitor` without `OwnerReference`s _before_ creating the Keycloak CRs; this approach has a number of downsides and pitfalls of course.

**Comment by andreaTP** [comment] 2022-02-15 10:58
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:58 UTC
Labels: impact/low, kind/feature
