### ISSUE TITLE
Add support for Microsoft SQL Server external database

### ISSUE THREAD

**Issue by oottka** [keycloak/keycloak-operator#439] opened 2022-01-03 15:15 UTC
### Description

Add support for Microsoft SQL Server external databases to allow users to use MS SQL server if they prefer to do so. Currently the keycloak-operator only supports PostgreSQL external databases, but keycloak itself has support for many database engines.

### Motivation

Currently keycloak-operator only supports PostgreSQL external databases. Providing a wider selection of options allows end users to choose the database they prefer. Support for MS SQL Server is already included in the [Keycloak docker image](https://github.com/keycloak/keycloak-containers/blob/main/server/README.md#database).

**Comment by andreaTP** [comment] 2022-01-13 16:19
Hi @oottka , at this point the entire team is mostly busy building a new operator for Keycloak.
You can find the design proposal here: https://github.com/keycloak/keycloak-community/pull/330 even there we are planning to support only PostgreSQL as it is the most widely used and the "opinionated" recommendation for a production environment.

Since in most Kubernetes offerings you have managed versions of Postgres, can you try to elaborate on the reasons behind this requirement?

**Comment by andreaTP** [comment] 2022-02-15 10:56
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:56 UTC
Labels: kind/enhancement, kind/feature, status/future
