### ISSUE TITLE
Support and related documentation for ingress controller other than nginx

### ISSUE THREAD

**Issue by shailsirohi** [keycloak/keycloak-operator#447] opened 2022-01-16 16:56 UTC
### Description

Currently, operator is hardcoded for nginx. I am running:
- traefik in production
- ambassador for my personal playground on kind cluster

Unable to find any documentation on how to get this working. 

### Motivation

There are multiple popular ingress controllers in the market. Keycloak operator should be ingress independent and able to work with any ingress controller

**Comment by andreaTP** [comment] 2022-01-21 10:01
Hi @shailsirohi ,

as you already noticed currently this operator only supports a default `nginx` ingress.

The (warmly)suggested approach(especially for production) is to disable the "provided default ingress" and spin up your own referring to the Keycloak created `Service`.

Let me know if this works for you.

**Comment by andreaTP** [comment] 2022-02-15 10:58
As this issue has been around for a long time we are closing this issue as out of date. If the issue is still valid, please verify with the latest version of the Keycloak operator, feel free to reopen and provide details to why it is still valid.

**Closed by andreaTP** 2022-02-15 10:58 UTC
Labels: impact/low, kind/enhancement

**Comment by danielwegener** [comment] 2022-03-29 13:22
How about allowing the operator to add annotations to the generated ingress (e.g. the by traefik required `ingress.kubernetes.io/protocol: https`). This could work similar like `keycloakDeploymentSpec` (suggestion: `keycloakIngress`) and merge fields provided in the CR over the generated ingress object.

**Comment by andreaTP** [comment] 2022-03-29 14:34
Hi @danielwegener , do you have any specific requirement to re-use the "default" ingress?
You are encouraged to spin your own `Ingress` and this allow to completely customize it.
